name: Start Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Prepare & Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: Spaccesi/flutter-actions-suite@main
        with:
          deploy-coverage-report: 'github-pages'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flutter-version: '3.41'
          license: 'false'
          test: 'true'
          analyze: 'true'
          coverage: 'true'
          license-fails-on-warnings: 'true'
          license-fails-on-info: 'true'
          compatible-licenses-conf-path: '.github/workflows/license_configuration.yaml'
      - uses: Spaccesi/flutter-actions-suite/release/build/web@main
      
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/web

