name: Start Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Spaccesi/flutter-actions-suite@main
        with:
          flutter-version: '3.41'
          flutter-channel: 'stable'
          run-test: 'true'
          run-analyze: 'true'
          run-license: 'true'
          run-coverage: 'true'
          analyze-fails-if-infos: 'false'
          analyze-fails-if-warnings: 'false'
          compatible-licenses-conf-path: '.github/workflows/compatible_licenses.yaml'
          test-create-coverage-badge: 'true'
          build-platform: 'web'
          build-mode: 'debug'
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Spaccesi/flutter-actions-suite@main
        with:
          flutter-version: '3.41'
          flutter-channel: 'stable'
          run-test: 'false'
          run-analyze: 'false'
          run-license: 'false'
          run-coverage: 'false'
          analyze-fails-if-infos: 'false'
          analyze-fails-if-warnings: 'false'
          compatible-licenses-conf-path: '.github/workflows/compatible_licenses.yaml'
          test-create-coverage-badge: 'false'
          build-platform: 'android'
          build-mode: 'debug'

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Spaccesi/flutter-actions-suite@main
        with:
          flutter-version: '3.41'
          flutter-channel: 'stable'
          run-test: 'false'
          run-analyze: 'false'
          run-license: 'false'
          run-coverage: 'false'
          analyze-fails-if-infos: 'false'
          analyze-fails-if-warnings: 'false'
          compatible-licenses-conf-path: '.github/workflows/compatible_licenses.yaml'
          test-create-coverage-badge: 'false'
          build-platform: 'linux'
          build-mode: 'debug'
        
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Spaccesi/flutter-actions-suite@main
        with:
          flutter-version: '3.41'
          flutter-channel: 'stable'
          run-test: 'false'
          run-analyze: 'false'
          run-license: 'false'
          run-coverage: 'false'
          analyze-fails-if-infos: 'false'
          analyze-fails-if-warnings: 'false'
          compatible-licenses-conf-path: '.github/workflows/compatible_licenses.yaml'
          test-create-coverage-badge: 'false'
          build-platform: 'windows'
          build-mode: 'debug'

          

